version: 0.2
phases:
  install:
    runtime-versions:
      python:3.11
  build:
    commands:
      - aws cloudformation package --template-file upload-to-search.yaml --s3-bucket docsearch-artifact --output-template-file upload.yaml

artifacts:
  type: zip
  files:
    - upload-to-search.yaml
    - upload.yaml
