AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function,upload to search.
Resources:
  uploadtosearch:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.handler
      Runtime: python3.11
      CodeUri: .
      Description: ''
      MemorySize: 512
      Timeout: 900
      Role: 'arn:aws:iam::662670180517:role/pro-search-lambda-role'
